# Form implementation generated from reading ui file 'telegram_news_bot.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 336)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 421, 271))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_start = QtWidgets.QLabel(self.widget)
        self.label_start.setObjectName("label_start")
        self.verticalLayout.addWidget(self.label_start)
        self.label_end = QtWidgets.QLabel(self.widget)
        self.label_end.setObjectName("label_end")
        self.verticalLayout.addWidget(self.label_end)
        self.label_kakao = QtWidgets.QLabel(self.widget)
        self.label_kakao.setObjectName("label_kakao")
        self.verticalLayout.addWidget(self.label_kakao)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.log_browser = QtWidgets.QTextBrowser(self.widget)
        self.log_browser.setObjectName("log_browser")
        self.verticalLayout.addWidget(self.log_browser)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 440, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Telegram News Bot"))
        self.label_start.setText(_translate("MainWindow", "* 프로그램 시작시 자동으로 크롤링이 시작됩니다."))
        self.label_end.setText(_translate("MainWindow", "* 프로그램 종료시 자동으로 크롤링이 종료됩니다."))
        self.label_kakao.setText(_translate("MainWindow", "* 프로그램 유지보수 및 제작 문의(카톡ID) : lazymarketer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
